server:
  port: 8770

spring:
  application:
    name: auth-service

auth:
  token:
    validity-seconds: 600
    signing-key: afaASuughBFN1212r
    issuer: auth-service
    claims:
      key:
        roles: roles
        id: id
  defaultUserRole: ROLE_USER